### ISSUE TITLE
4.0 Compatibility

### ISSUE THREAD

**Issue by JerikoOne** [chrisbeluga/kirby-navigation#40]
Currently the plugin is not compatible with 4.0 (as of writing this issue: Beta 1):

The API route isn't working
![image](https://github.com/chrisbeluga/kirby-navigation/assets/3002580/a5859037-30cf-427f-8df0-4a6f98f6776f)

The select isn't styled correctly
<img width="274" alt="image" src="https://github.com/chrisbeluga/kirby-navigation/assets/3002580/ffc7b00a-9f0d-4785-afea-beef1562801b">

**Comment by distantnative** [comment]
To fix you could add the following styles

```css
.navigation-field .k-dropdown-content {
  --button-height: auto;
}
```
