### ISSUE TITLE
Field "primarymenu": The field type "navigation" does not exist

### ISSUE THREAD

**Issue by t0b1hh** [chrisbeluga/kirby-navigation#53]
I am trying to get this plugin to work with kirby 4.8.0 + chrisbeluga/navigation 4.1.3 (latest)

Tried installing as git submodule and also via composer. Cleared the cache and also made a plugin repuild via npm in the plugin folder, but always get the message " Field "primarymenu": The field type "navigation" does not exist" in my panel.

my site.yml has the following code. Based on the kirby starterkit i added 

```
      ## Main navigation
      menus:
        type: fields
        fields:
          primarymenu:
            type: navigation
            label: Main Menu
            levels: 5
```

any idea how to solve this?

![Image](https://github.com/user-attachments/assets/bcdb1d31-b1e0-4f50-811b-a752bc49bdf0)
