### ISSUE TITLE
Save/Revert controls are always displayed

### ISSUE THREAD

**Issue by gearsdigital** [chrisbeluga/kirby-navigation#56]
I recently upgraded to Kirby 5 along with kirby-navigation 5 (locally using [Herd](https://herd.laravel.com)), and ran into a small –but mildly annoying– issue: the orange Save/Revert controls are always visible, even when no changes have been made. (Saving itself works perfectly fine 😊)

If I remove the field, the controls behave correctly. That is my field config:

```yml
# site.yml
tabs:
  content:
    label: Seiten
    icon: text
    columns:
      right:
        width: 1/2
        sections:
          content:
            type: fields
            fields:
              primary:
                label: Primärnavigation
                type: navigation
                levels: 2
                width: 1/2
```

![Image](https://github.com/user-attachments/assets/fd0b75a0-bd2d-4b25-9aa9-c0dab3c7389b)
![Image](https://github.com/user-attachments/assets/bf96a9fa-5993-4d92-b54f-995f5ea3dbf7)

Let me know if you need more details or a MRE.
